# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/martijn/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/martijn/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martijn/Projects/aoc2021

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martijn/Projects/aoc2021

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/martijn/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/martijn/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martijn/Projects/aoc2021/CMakeFiles /home/martijn/Projects/aoc2021//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martijn/Projects/aoc2021/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named day1

# Build rule for target.
day1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 day1
.PHONY : day1

# fast build rule for target.
day1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day1.dir/build.make CMakeFiles/day1.dir/build
.PHONY : day1/fast

#=============================================================================
# Target rules for targets named day2

# Build rule for target.
day2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 day2
.PHONY : day2

# fast build rule for target.
day2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day2.dir/build.make CMakeFiles/day2.dir/build
.PHONY : day2/fast

#=============================================================================
# Target rules for targets named day3

# Build rule for target.
day3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 day3
.PHONY : day3

# fast build rule for target.
day3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day3.dir/build.make CMakeFiles/day3.dir/build
.PHONY : day3/fast

#=============================================================================
# Target rules for targets named day7

# Build rule for target.
day7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 day7
.PHONY : day7

# fast build rule for target.
day7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day7.dir/build.make CMakeFiles/day7.dir/build
.PHONY : day7/fast

src/day1.o: src/day1.cpp.o
.PHONY : src/day1.o

# target to build an object file
src/day1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day1.dir/build.make CMakeFiles/day1.dir/src/day1.cpp.o
.PHONY : src/day1.cpp.o

src/day1.i: src/day1.cpp.i
.PHONY : src/day1.i

# target to preprocess a source file
src/day1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day1.dir/build.make CMakeFiles/day1.dir/src/day1.cpp.i
.PHONY : src/day1.cpp.i

src/day1.s: src/day1.cpp.s
.PHONY : src/day1.s

# target to generate assembly for a file
src/day1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day1.dir/build.make CMakeFiles/day1.dir/src/day1.cpp.s
.PHONY : src/day1.cpp.s

src/day2.o: src/day2.cpp.o
.PHONY : src/day2.o

# target to build an object file
src/day2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day2.dir/build.make CMakeFiles/day2.dir/src/day2.cpp.o
.PHONY : src/day2.cpp.o

src/day2.i: src/day2.cpp.i
.PHONY : src/day2.i

# target to preprocess a source file
src/day2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day2.dir/build.make CMakeFiles/day2.dir/src/day2.cpp.i
.PHONY : src/day2.cpp.i

src/day2.s: src/day2.cpp.s
.PHONY : src/day2.s

# target to generate assembly for a file
src/day2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day2.dir/build.make CMakeFiles/day2.dir/src/day2.cpp.s
.PHONY : src/day2.cpp.s

src/day3.o: src/day3.cpp.o
.PHONY : src/day3.o

# target to build an object file
src/day3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day3.dir/build.make CMakeFiles/day3.dir/src/day3.cpp.o
.PHONY : src/day3.cpp.o

src/day3.i: src/day3.cpp.i
.PHONY : src/day3.i

# target to preprocess a source file
src/day3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day3.dir/build.make CMakeFiles/day3.dir/src/day3.cpp.i
.PHONY : src/day3.cpp.i

src/day3.s: src/day3.cpp.s
.PHONY : src/day3.s

# target to generate assembly for a file
src/day3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day3.dir/build.make CMakeFiles/day3.dir/src/day3.cpp.s
.PHONY : src/day3.cpp.s

src/day7.o: src/day7.cpp.o
.PHONY : src/day7.o

# target to build an object file
src/day7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day7.dir/build.make CMakeFiles/day7.dir/src/day7.cpp.o
.PHONY : src/day7.cpp.o

src/day7.i: src/day7.cpp.i
.PHONY : src/day7.i

# target to preprocess a source file
src/day7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day7.dir/build.make CMakeFiles/day7.dir/src/day7.cpp.i
.PHONY : src/day7.cpp.i

src/day7.s: src/day7.cpp.s
.PHONY : src/day7.s

# target to generate assembly for a file
src/day7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day7.dir/build.make CMakeFiles/day7.dir/src/day7.cpp.s
.PHONY : src/day7.cpp.s

src/load_inputs.o: src/load_inputs.cpp.o
.PHONY : src/load_inputs.o

# target to build an object file
src/load_inputs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day1.dir/build.make CMakeFiles/day1.dir/src/load_inputs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day2.dir/build.make CMakeFiles/day2.dir/src/load_inputs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day3.dir/build.make CMakeFiles/day3.dir/src/load_inputs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day7.dir/build.make CMakeFiles/day7.dir/src/load_inputs.cpp.o
.PHONY : src/load_inputs.cpp.o

src/load_inputs.i: src/load_inputs.cpp.i
.PHONY : src/load_inputs.i

# target to preprocess a source file
src/load_inputs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day1.dir/build.make CMakeFiles/day1.dir/src/load_inputs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day2.dir/build.make CMakeFiles/day2.dir/src/load_inputs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day3.dir/build.make CMakeFiles/day3.dir/src/load_inputs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day7.dir/build.make CMakeFiles/day7.dir/src/load_inputs.cpp.i
.PHONY : src/load_inputs.cpp.i

src/load_inputs.s: src/load_inputs.cpp.s
.PHONY : src/load_inputs.s

# target to generate assembly for a file
src/load_inputs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day1.dir/build.make CMakeFiles/day1.dir/src/load_inputs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day2.dir/build.make CMakeFiles/day2.dir/src/load_inputs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day3.dir/build.make CMakeFiles/day3.dir/src/load_inputs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/day7.dir/build.make CMakeFiles/day7.dir/src/load_inputs.cpp.s
.PHONY : src/load_inputs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... day1"
	@echo "... day2"
	@echo "... day3"
	@echo "... day7"
	@echo "... src/day1.o"
	@echo "... src/day1.i"
	@echo "... src/day1.s"
	@echo "... src/day2.o"
	@echo "... src/day2.i"
	@echo "... src/day2.s"
	@echo "... src/day3.o"
	@echo "... src/day3.i"
	@echo "... src/day3.s"
	@echo "... src/day7.o"
	@echo "... src/day7.i"
	@echo "... src/day7.s"
	@echo "... src/load_inputs.o"
	@echo "... src/load_inputs.i"
	@echo "... src/load_inputs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

